### ISSUE TITLE
ConsoleIO Glitches

### ISSUE THREAD

**Issue by TheKingEagle** [rmsoftware-development/RMSoftware.ModularBot#9]
**Describe the bug**
Occasionally the Console will output and cause UI to garble. This has been an on-going issue since v1.0.
Occasionally Console position isn't registered, so ConsoleIO will not properly set cursor position back when issuing restart or shutdown commands. Some Command input text is also left on screen if it exceeds the length of the output result, that is supposed to overwrite what the user input.

Text will also garble if the window is resized to larger than buffer. *Windows 10 only*

**To Reproduce**
Unfortunately this seems to happen at random. Typically if console is resized, or if too many write events try to happen at the same time.

**Expected behavior**
Console output is CLEAN, and free of line mismatching.
`ScreenBusy`, and `Busy` wait conditions were added to try and minimize this, but this does not always work.

**Screenshots**
[![Fail01](https://cdn.rms0.org/img/issue/fail01.png)](https://cdn.rms0.org/img/issue/fail01.png)

**Desktop Environments:**
 - Windows 10 Professional
 - Windows Server 2012 R2
 - ModularBOT v1.0 thru current.

**Additional context**

**Comment by rmsoftware-development** [comment]
Latest commit looks promising, however there's probably a better way.

**Comment by TheKingEagle** [comment]
6704a03 is causing a huge performance hit.

Thread.sleep, while even for 1MS, will add up quickly. 

**OS**: Windows Server 2012 - R2

**Comment by TheKingEagle** [comment]
ccfd749 has dramatically improved performance by fixing what 6704a03 introduced. This commit is still undergoing lengthy testing, so I can't say problem solved just yet.

There is a new bug introduced by ccfd749 with console command `config.setloglevel`

**Comment by TheKingEagle** [comment]
Update for this issue, Console wrapping does not clear the entire width of the window...

For example, writing a line with 140 characters, then writing a line with 100 will only replace 100 characters from the output.
![image](https://user-images.githubusercontent.com/30922258/59135066-92cd6e80-894b-11e9-9292-f8306c51a61f.png)

**Comment by TheKingEagle** [comment]
Another update for this issue: Occasionally the console will completely seize up, which is to say, it will no longer queue log entries, or appear to process console input properly.

**Comment by TheKingEagle** [comment]
I've made some progress on this issue. IO glitches (garbled text) is not an issue unless you abuse console with an AutoHotkey script (LOL)... ConsoleIO Queue is still just a bit too messy, as I'm still encountering some deadlock. It's almost like a screen check is being passed over, and not resetting after the write operation is finished, which causes the console to become locked up.

**Comment by TheKingEagle** [comment]
After a week of testing, I can say 1e4ae23 looks to have solved the console deadlock. That brings the majority of the ConsoleIO issue to a close.

The final problem - SOLVED: The entry queue was never hitting zero because some of the log entries were above the program's output level threshold, and as a result, the thread would get stuck in an infinite loop trying to process filtered logs.

This issue will be closed for now.
